#!/usr/bin/env python3
"""
rebrand_to_billproof.py

Renames the product from "ATVR Narrative Generator" to "Billproof" inside
index.html. Run this once on your repo's index.html and commit the result.

ATVR (Action / Task / Value / Result) is preserved everywhere it refers to
the underlying methodology - only the product brand changes.

Usage:
    cd /path/to/your/repo
    python3 rebrand_to_billproof.py

Dry-run first if you want to preview without writing:
    python3 rebrand_to_billproof.py --dry-run

The script backs up the original to index.html.bak before writing.
"""
import sys
import shutil
import argparse
from pathlib import Path

INPUT_FILE = "index.html"
BACKUP_FILE = "index.html.bak"

# Each tuple is (old_string, new_string, description).
# Listed in the order they appear in the file.
REPLACEMENTS = [
    (
        "<title>ATVR Narrative Generator | The Billing Coach</title>",
        "<title>Billproof | The Billing Coach</title>",
        "Browser tab title"
    ),
    (
        '<h2 style="margin:0 0 8px;color:#1e2d4a;font-size:22px;">ATVR Narrative Generator</h2>',
        '<h2 style="margin:0 0 8px;color:#1e2d4a;font-size:22px;">Billproof</h2>',
        "Access gate heading (login overlay)"
    ),
    (
        'if (!confirm("Log out of the ATVR Generator?")) return;',
        'if (!confirm("Log out of Billproof?")) return;',
        "Logout confirmation prompt"
    ),
    (
        "<h1>The <em>ATVR</em> Narrative Generator</h1>",
        "<h1>Bill<em>proof</em></h1>",
        "Hero heading (gold italic accent on 'proof')"
    ),
    (
        '<p>Bill Your Time Today - the easy way. Turn any task blurb into a polished and client compliant billing narrative in seconds. Mindset-aware coaching baked into every narrative. Powered by the ATVR Framework.</p>',
        "<p>Bill Your Time Today - the better way. Turn any billable task into a polished and client compliant billing narrative in seconds. The value of your legal services can never be assumed by your clients - it's communicated.</p>",
        "Hero tagline (new positioning)"
    ),
    (
        "<h2>How to Use the <em>ATVR</em> Generator</h2>",
        "<h2>How to Use Bill<em>proof</em></h2>",
        "Help modal heading"
    ),
    (
        "Generated by ATVR Narrative Generator \u00b7 The Billing Coach \u00b7 thebillingcoach.com",
        "Generated by Billproof \u00b7 The Billing Coach \u00b7 thebillingcoach.com",
        "Word doc export footer (appears in 2 places: Pro Forma + Month-End exports)"
    ),
]


def main():
    parser = argparse.ArgumentParser(description="Rebrand index.html to Billproof")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would change without writing")
    parser.add_argument("--file", default=INPUT_FILE,
                        help=f"File to edit (default: {INPUT_FILE})")
    args = parser.parse_args()

    path = Path(args.file)
    if not path.exists():
        print(f"ERROR: {args.file} not found in the current directory.")
        print("Run this script from the same folder as your index.html.")
        sys.exit(1)

    text = path.read_text(encoding="utf-8")
    original = text
    summary = []

    for old, new, description in REPLACEMENTS:
        count = text.count(old)
        if count == 0:
            summary.append((description, "NOT FOUND", 0))
            continue
        text = text.replace(old, new)
        summary.append((description, "REPLACED", count))

    print("Rebrand summary")
    print("=" * 70)
    for desc, status, count in summary:
        marker = "[OK]" if status == "REPLACED" else "[--]"
        suffix = f"({count} occurrence{'s' if count != 1 else ''})"
        print(f"  {marker} {desc:50s} {status} {suffix}")
    print("=" * 70)

    if text == original:
        print("\nNo changes needed - file is already up to date.")
        return

    # Warn if anything wasn't found, since that means the file may have changed
    # since this script was written
    missing = [d for d, s, _ in summary if s == "NOT FOUND"]
    if missing:
        print("\nWARNING: Some replacements were not found in the file:")
        for d in missing:
            print(f"  - {d}")
        print("These were probably already changed, or the file has been edited.")
        print("Review the summary above. If anything looks wrong, revert.")

    if args.dry_run:
        print("\n--dry-run was set. No files were written.")
        return

    # Backup first
    shutil.copy(path, BACKUP_FILE)
    print(f"\nOriginal backed up to {BACKUP_FILE}")

    path.write_text(text, encoding="utf-8")
    print(f"Wrote rebranded {args.file}")

    print("\nNext steps:")
    print("  1. Open the page in a browser (locally or in dev) and check:")
    print("     - Login screen says 'Billproof'")
    print("     - Hero heading shows 'Bill' + 'proof' (gold italic on 'proof')")
    print("     - Browser tab title says 'Billproof | The Billing Coach'")
    print("     - Help modal heading says 'How to Use Billproof'")
    print("  2. git add index.html")
    print("  3. git commit -m \"Rebrand from ATVR Narrative Generator to Billproof\"")
    print("  4. git push")
    print("\nIf anything looks broken, restore from index.html.bak:")
    print(f"  mv {BACKUP_FILE} {INPUT_FILE}")


if __name__ == "__main__":
    main()
